-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS a_bronze."T_DIM_ANFITRIAO"
(
    host_id bigint NOT NULL,
    fk_anuncio bigint NOT NULL,
    host_url text COLLATE pg_catalog."default",
    host_name text COLLATE pg_catalog."default",
    host_since date,
    host_location text COLLATE pg_catalog."default",
    host_about text COLLATE pg_catalog."default",
    host_response_time text COLLATE pg_catalog."default",
    host_response_rate text COLLATE pg_catalog."default",
    host_is_superhost text COLLATE pg_catalog."default",
    host_thumbnail_url text COLLATE pg_catalog."default",
    host_picture_url text COLLATE pg_catalog."default",
    host_neighbourhood text COLLATE pg_catalog."default",
    host_listings_count numeric,
    host_total_listings_count numeric,
    host_verifications text COLLATE pg_catalog."default",
    host_has_profile_pic text COLLATE pg_catalog."default",
    host_identity_verified text COLLATE pg_catalog."default",
    CONSTRAINT "T_DIM_ANFITRIAO_pkey" PRIMARY KEY (host_id)
);

CREATE TABLE IF NOT EXISTS a_bronze."T_DIM_ANUNCIO"
(
    id_anuncio bigint NOT NULL,
    listing_url text COLLATE pg_catalog."default",
    scrape_id bigint,
    name text COLLATE pg_catalog."default",
    summary text COLLATE pg_catalog."default",
    space text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    experiences_offered text COLLATE pg_catalog."default",
    neighborhood_overview text COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    transit text COLLATE pg_catalog."default",
    access text COLLATE pg_catalog."default",
    interaction text COLLATE pg_catalog."default",
    house_rules text COLLATE pg_catalog."default",
    picture_url text COLLATE pg_catalog."default",
    CONSTRAINT "T_DIM_ANUNCIO_pkey" PRIMARY KEY (id_anuncio)
);

CREATE TABLE IF NOT EXISTS a_bronze."T_DIM_LOCALIZACAO"
(
    id_localizacao serial NOT NULL,
    fk_anuncio bigint NOT NULL,
    street text COLLATE pg_catalog."default",
    neighbourhood text COLLATE pg_catalog."default",
    neighbourhood_cleansed text COLLATE pg_catalog."default",
    city text COLLATE pg_catalog."default",
    state text COLLATE pg_catalog."default",
    zipcode text COLLATE pg_catalog."default",
    market text COLLATE pg_catalog."default",
    smart_location text COLLATE pg_catalog."default",
    country_code text COLLATE pg_catalog."default",
    country text COLLATE pg_catalog."default",
    latitude numeric(10, 6),
    longitude numeric(10, 6),
    is_location_exact text COLLATE pg_catalog."default",
    CONSTRAINT "T_DIM_LOCALIZACAO_pkey" PRIMARY KEY (id_localizacao)
);

CREATE TABLE IF NOT EXISTS a_bronze."T_DIM_PROPRIEDADE"
(
    id_propriedade bigserial NOT NULL,
    fk_anuncio bigint,
    property_type text COLLATE pg_catalog."default",
    room_type text COLLATE pg_catalog."default",
    accommodates integer,
    bathrooms numeric,
    bedrooms numeric,
    beds numeric,
    bed_type text COLLATE pg_catalog."default",
    amenities text COLLATE pg_catalog."default",
    minimum_nights numeric,
    maximum_nights numeric,
    calendar_updated text COLLATE pg_catalog."default",
    has_availability text COLLATE pg_catalog."default",
    availability_30 numeric,
    availability_60 numeric,
    availability_90 numeric,
    availability_365 numeric,
    CONSTRAINT "T_DIM_PROPRIEDADE_pkey" PRIMARY KEY (id_propriedade)
);

CREATE TABLE IF NOT EXISTS a_bronze."T_DIM_REGRAS"
(
    id_regras bigserial NOT NULL,
    fk_anuncio bigint,
    requires_license text COLLATE pg_catalog."default",
    instant_bookable text COLLATE pg_catalog."default",
    is_business_travel_ready text COLLATE pg_catalog."default",
    cancellation_policy text COLLATE pg_catalog."default",
    require_guest_profile_picture text COLLATE pg_catalog."default",
    require_guest_phone_verification text COLLATE pg_catalog."default",
    calculated_host_listings_count integer,
    minimum_minimum_nights integer,
    maximum_minimum_nights integer,
    minimum_maximum_nights integer,
    maximum_maximum_nights integer,
    minimum_nights_avg_ntm integer,
    maximum_nights_avg_ntm integer,
    calculated_host_listings_count_entire_homes integer,
    calculated_host_listings_count_private_rooms integer,
    calculated_host_listings_count_shared_rooms integer,
    CONSTRAINT "T_DIM_REGRAS_pkey" PRIMARY KEY (id_regras),
    CONSTRAINT "T_DIM_REGRAS_fk_anuncio_key" UNIQUE (fk_anuncio)
);

CREATE TABLE IF NOT EXISTS a_bronze."T_FATO_AVALIACAO"
(
    id_reviews bigserial NOT NULL,
    fk_anuncio bigint,
    number_of_reviews numeric,
    first_review date,
    last_review date,
    review_scores_rating numeric,
    review_scores_accuracy numeric,
    review_scores_cleanliness numeric,
    review_scores_checkin numeric,
    review_scores_communication numeric,
    review_scores_location numeric,
    review_scores_value numeric,
    reviews_per_month numeric,
    number_of_reviews_ltm text COLLATE pg_catalog."default",
    CONSTRAINT "T_FATO_AVALIACAO_pkey" PRIMARY KEY (id_reviews)
);

CREATE TABLE IF NOT EXISTS a_bronze."T_FATO_PRECIFICACAO"
(
    id_preco serial NOT NULL,
    fk_anuncio bigint,
    price numeric(10, 2),
    security_deposit numeric(10, 2),
    cleaning_fee numeric(10, 2),
    guests_included integer,
    extra_people numeric(10, 2),
    last_scraped date,
    calendar_last_scraped date,
    CONSTRAINT "T_FATO_PRECIFICACAO_pkey" PRIMARY KEY (id_preco)
);

CREATE TABLE IF NOT EXISTS a_bronze.processamento_arquivos
(
    id serial NOT NULL,
    nome_arquivo text COLLATE pg_catalog."default",
    data_processamento timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT processamento_arquivos_pkey PRIMARY KEY (id),
    CONSTRAINT processamento_arquivos_nome_arquivo_key UNIQUE (nome_arquivo)
);

ALTER TABLE IF EXISTS a_bronze."T_DIM_ANFITRIAO"
    ADD CONSTRAINT "T_DIM_ANFITRIAO_fk_anuncio_fkey" FOREIGN KEY (fk_anuncio)
    REFERENCES a_bronze."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS a_bronze."T_DIM_LOCALIZACAO"
    ADD CONSTRAINT "T_DIM_LOCALIZACAO_fk_anuncio_fkey" FOREIGN KEY (fk_anuncio)
    REFERENCES a_bronze."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS a_bronze."T_DIM_PROPRIEDADE"
    ADD CONSTRAINT "T_DIM_PROPRIEDADE_fk_anuncio_fkey" FOREIGN KEY (fk_anuncio)
    REFERENCES a_bronze."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS a_bronze."T_DIM_REGRAS"
    ADD CONSTRAINT "T_DIM_REGRAS_fk_anuncio_fkey" FOREIGN KEY (fk_anuncio)
    REFERENCES a_bronze."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "T_DIM_REGRAS_fk_anuncio_key"
    ON a_bronze."T_DIM_REGRAS"(fk_anuncio);


ALTER TABLE IF EXISTS a_bronze."T_FATO_AVALIACAO"
    ADD CONSTRAINT "T_FATO_AVALIACAO_fk_anuncio_fkey" FOREIGN KEY (fk_anuncio)
    REFERENCES a_bronze."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS a_bronze."T_FATO_PRECIFICACAO"
    ADD CONSTRAINT "T_FATO_PRECIFICACAO_fk_anuncio_fkey" FOREIGN KEY (fk_anuncio)
    REFERENCES a_bronze."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;