-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS b_silver."T_DIM_ANFITRIAO"
(
    host_id bigint NOT NULL,
    host_url text COLLATE pg_catalog."default",
    host_name text COLLATE pg_catalog."default",
    host_since date,
    host_location text COLLATE pg_catalog."default",
    host_about text COLLATE pg_catalog."default",
    host_response_time text COLLATE pg_catalog."default",
    host_response_rate numeric(5, 4),
    host_is_superhost boolean,
    host_thumbnail_url text COLLATE pg_catalog."default",
    host_picture_url text COLLATE pg_catalog."default",
    host_neighbourhood text COLLATE pg_catalog."default",
    host_listings_count integer,
    host_total_listings_count integer,
    host_verifications text COLLATE pg_catalog."default",
    host_has_profile_pic boolean,
    host_identity_verified boolean,
    fonte text COLLATE pg_catalog."default" DEFAULT 'airbnb_csv'::text,
    dt_ingestao timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "T_DIM_ANFITRIAO_pkey" PRIMARY KEY (host_id)
);

CREATE TABLE IF NOT EXISTS b_silver."T_DIM_ANUNCIO"
(
    id_anuncio bigint NOT NULL,
    listing_url text COLLATE pg_catalog."default",
    scrape_id bigint,
    name text COLLATE pg_catalog."default",
    summary text COLLATE pg_catalog."default",
    space text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    neighborhood_overview text COLLATE pg_catalog."default",
    transit text COLLATE pg_catalog."default",
    access text COLLATE pg_catalog."default",
    interaction text COLLATE pg_catalog."default",
    house_rules text COLLATE pg_catalog."default",
    picture_url text COLLATE pg_catalog."default",
    fonte text COLLATE pg_catalog."default" DEFAULT 'airbnb_csv'::text,
    dt_ingestao timestamp without time zone NOT NULL DEFAULT now(),
    host_id bigint,
    CONSTRAINT "T_DIM_ANUNCIO_pkey" PRIMARY KEY (id_anuncio)
);

CREATE TABLE IF NOT EXISTS b_silver."T_DIM_LOCALIZACAO"
(
    id_localizacao bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fk_anuncio bigint NOT NULL,
    street text COLLATE pg_catalog."default",
    city text COLLATE pg_catalog."default",
    state text COLLATE pg_catalog."default",
    zipcode text COLLATE pg_catalog."default",
    market text COLLATE pg_catalog."default",
    smart_location text COLLATE pg_catalog."default",
    country_code character(2) COLLATE pg_catalog."default",
    country text COLLATE pg_catalog."default",
    latitude numeric(9, 6),
    longitude numeric(9, 6),
    is_location_exact boolean,
    neighbourhood text COLLATE pg_catalog."default",
    regiao_adm text COLLATE pg_catalog."default",
    rp text COLLATE pg_catalog."default",
    dist_cristo_redentor_km numeric(10, 4),
    dist_pao_de_acucar_km numeric(10, 4),
    dist_praia_de_copacabana_km numeric(10, 4),
    dist_praia_de_ipanema_km numeric(10, 4),
    dist_maracana_km numeric(10, 4),
    dist_arcos_da_lapa_km numeric(10, 4),
    dist_museu_do_amanha_km numeric(10, 4),
    dist_jardim_botanico_km numeric(10, 4),
    nearest_poi_km numeric(10, 4),
    nearest_poi_name text COLLATE pg_catalog."default",
    fonte text COLLATE pg_catalog."default" DEFAULT 'Airbnb_bronze'::text,
    dt_ingestao timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "T_DIM_LOCALIZACAO_pkey" PRIMARY KEY (id_localizacao)
);

CREATE TABLE IF NOT EXISTS b_silver."T_DIM_PROPRIEDADE"
(
    id_propriedade bigserial NOT NULL,
    fk_anuncio bigint NOT NULL,
    room_type_std text COLLATE pg_catalog."default" NOT NULL,
    property_type_std text COLLATE pg_catalog."default" NOT NULL,
    bed_type_std text COLLATE pg_catalog."default" NOT NULL,
    accommodates integer NOT NULL,
    bathrooms numeric(4, 1),
    bedrooms integer,
    beds integer,
    amenities_count integer,
    has_wifi boolean,
    has_ac boolean,
    has_pool boolean,
    has_kitchen boolean,
    has_washer boolean,
    has_dryer boolean,
    has_heating boolean,
    has_tv boolean,
    has_availability boolean,
    availability_30 integer,
    availability_60 integer,
    availability_90 integer,
    availability_365 integer,
    minimum_nights integer,
    maximum_nights integer,
    fonte text COLLATE pg_catalog."default" DEFAULT 'Airbnb_bronze'::text,
    dt_ingestao timestamp without time zone DEFAULT now(),
    CONSTRAINT "T_DIM_PROPRIEDADE_pkey" PRIMARY KEY (id_propriedade),
    CONSTRAINT ux_prop_fk_anuncio UNIQUE (fk_anuncio)
);

CREATE TABLE IF NOT EXISTS b_silver."T_DIM_REGRAS"
(
    id_regras bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fk_anuncio bigint NOT NULL,
    requires_license boolean,
    instant_bookable boolean,
    is_business_travel_ready boolean,
    cancellation_policy character varying(32) COLLATE pg_catalog."default",
    require_guest_profile_picture boolean,
    require_guest_phone_verification boolean,
    calculated_host_listings_count integer,
    requires_any_verification boolean,
    cancellation_strictness smallint,
    fonte text COLLATE pg_catalog."default" NOT NULL DEFAULT 'Airbnb_bronze'::text,
    dt_ingestao timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "T_DIM_REGRAS_pkey" PRIMARY KEY (id_regras)
);

CREATE TABLE IF NOT EXISTS b_silver."T_FATO_AVALIACAO"
(
    id_reviews bigint NOT NULL,
    fk_anuncio bigint NOT NULL,
    number_of_reviews integer,
    number_of_reviews_ltm integer,
    reviews_per_month numeric(10, 4),
    first_review date,
    last_review date,
    duracao_reviews_dias integer,
    ativo_anos numeric(10, 4),
    reviews_por_ano numeric(12, 4),
    review_scores_rating_0_10 numeric(4, 2),
    review_scores_accuracy_0_10 numeric(4, 2),
    review_scores_cleanliness_0_10 numeric(4, 2),
    review_scores_checkin_0_10 numeric(4, 2),
    review_scores_communication_0_10 numeric(4, 2),
    review_scores_location_0_10 numeric(4, 2),
    review_scores_value_0_10 numeric(4, 2),
    nota_media_0_10 numeric(4, 2),
    densidade_reviews_ltm numeric(6, 4),
    tem_review smallint,
    fonte text COLLATE pg_catalog."default" DEFAULT 'Airbnb_bronze'::text,
    dt_ingestao timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "T_FATO_AVALIACAO_pkey" PRIMARY KEY (id_reviews)
);

CREATE TABLE IF NOT EXISTS b_silver."T_FATO_PRECIFICACAO"
(
    id_preco bigint NOT NULL,
    fk_anuncio bigint NOT NULL,
    price numeric(12, 2),
    security_deposit numeric(12, 2),
    cleaning_fee numeric(12, 2),
    guests_included integer,
    extra_people numeric(12, 2),
    last_scraped date,
    calendar_last_scraped date,
    has_cleaning_fee smallint,
    has_deposit smallint,
    cleaning_fee_ratio numeric(8, 4),
    deposit_ratio numeric(8, 4),
    price_per_included_guest numeric(12, 2),
    price_2p_nightly numeric(12, 2),
    price_4p_nightly numeric(12, 2),
    fonte text COLLATE pg_catalog."default" DEFAULT 'Airbnb_bronze'::text,
    dt_ingestao timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "T_FATO_PRECIFICACAO_pkey" PRIMARY KEY (id_preco)
);

ALTER TABLE IF EXISTS b_silver."T_DIM_ANUNCIO"
    ADD CONSTRAINT fk_anuncio_host FOREIGN KEY (host_id)
    REFERENCES b_silver."T_DIM_ANFITRIAO" (host_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS idx_dim_anuncio_host_id
    ON b_silver."T_DIM_ANUNCIO"(host_id);


ALTER TABLE IF EXISTS b_silver."T_DIM_LOCALIZACAO"
    ADD CONSTRAINT fk_localizacao_anuncio FOREIGN KEY (fk_anuncio)
    REFERENCES b_silver."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ux_localizacao_fk_anuncio
    ON b_silver."T_DIM_LOCALIZACAO"(fk_anuncio);


ALTER TABLE IF EXISTS b_silver."T_DIM_PROPRIEDADE"
    ADD CONSTRAINT fk_anuncio_propriedade FOREIGN KEY (fk_anuncio)
    REFERENCES b_silver."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_propriedade_fk_anuncio
    ON b_silver."T_DIM_PROPRIEDADE"(fk_anuncio);


ALTER TABLE IF EXISTS b_silver."T_DIM_REGRAS"
    ADD CONSTRAINT fk_regras_anuncio FOREIGN KEY (fk_anuncio)
    REFERENCES b_silver."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS uq_regras_fk_anuncio
    ON b_silver."T_DIM_REGRAS"(fk_anuncio);


ALTER TABLE IF EXISTS b_silver."T_FATO_AVALIACAO"
    ADD CONSTRAINT fk_avaliacao_anuncio FOREIGN KEY (fk_anuncio)
    REFERENCES b_silver."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_fato_avaliacao_fk_anuncio
    ON b_silver."T_FATO_AVALIACAO"(fk_anuncio);


ALTER TABLE IF EXISTS b_silver."T_FATO_PRECIFICACAO"
    ADD CONSTRAINT fk_precificacao_anuncio FOREIGN KEY (fk_anuncio)
    REFERENCES b_silver."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_precificacao_fk_anuncio
    ON b_silver."T_FATO_PRECIFICACAO"(fk_anuncio);

END;