-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS b_silver."T_DIM_ANUNCIO"
(
    id_anuncio bigint NOT NULL,
    listing_url text,
    scrape_id integer,
    last_scraped date,
    calendar_last_scraped date,
    name text,
    summary text,
    space text,
    description text,
    experiences_offered text,
    neighborhood_overview text,
    notes text,
    transit text,
    access text,
    interaction text,
    house_rules text,
    picture_url text,
    PRIMARY KEY (id_anuncio)
);

CREATE TABLE IF NOT EXISTS b_silver."T_DIM_ANFITRIAO"
(
    host_id bigint NOT NULL,
    fk_anuncio bigint NOT NULL,
    host_url text,
    host_name text,
    host_since date,
    host_location text,
    host_about text,
    host_response_time text,
    host_response_rate numeric,
    host_is_superhost text,
    host_thumbnail_url text,
    host_picture_url text,
    host_neighbourhood text,
    host_listings_count numeric,
    host_total_listings_count numeric,
    host_verifications text,
    host_has_profile_pic text,
    host_identity_verified text
);

CREATE TABLE IF NOT EXISTS b_silver."T_DIM_LOCALIZACAO"
(
    id_localizacao serial NOT NULL,
    fk_anuncio bigint NOT NULL,
    street text,
    neighbourhood text,
    neighbourhood_cleansed text,
    city text,
    state text,
    zipcode text,
    market text,
    smart_location text,
    country_code text,
    country text,
    latitude numeric(10, 6),
    longitude numeric(10, 6),
    is_location_exact text,
    PRIMARY KEY (id_localizacao)
);

CREATE TABLE IF NOT EXISTS b_silver."T_DIM_PROPRIEDADE"
(
    id_propriedade serial,
    fk_anuncio bigint,
    property_type text,
    room_type text,
    accommodates integer,
    bathrooms integer,
    bedrooms integer,
    beds integer,
    bed_type text,
    amenities text,
    minimum_nights integer,
    maximum_nights integer,
    calendar_updated text,
    has_availability text,
    availability_30 integer,
    availability_60 integer,
    availability_90 integer,
    availability_365 integer,
    PRIMARY KEY (id_propriedade)
);

CREATE TABLE IF NOT EXISTS b_silver."T_FATO_PRECIFICACAO"
(
    id_preco serial,
    fk_anuncio bigint,
    price numeric(10, 2),
    security_deposit numeric(10, 2),
    cleaning_fee numeric(10, 2),
    guests_included integer,
    extra_people numeric(10, 2),
    PRIMARY KEY (id_preco)
);

CREATE TABLE IF NOT EXISTS b_silver."T_FATO_AVALIACAO"
(
    id_reviews serial,
    fk_anuncio bigint,
    number_of_reviews integer,
    first_review date,
    last_review date,
    review_scores_rating integer,
    review_scores_accuracy numeric(4, 2),
    review_scores_cleanliness numeric(4, 2),
    review_scores_checkin numeric(4, 2),
    review_scores_communication numeric(4, 2),
    review_scores_location numeric(4, 2),
    review_scores_value numeric(4, 2),
    reviews_per_month numeric(5, 2),
    number_of_reviews_ltm text,
    PRIMARY KEY (id_reviews)
);

CREATE TABLE IF NOT EXISTS b_silver."T_DIM_REGRAS"
(
    id_regras serial,
    fk_anuncio bigint,
    requires_license text,
    instant_bookable text,
    is_business_travel_ready text,
    cancellation_policy text,
    require_guest_profile_picture text,
    require_guest_phone_verification text,
    calculated_host_listings_count integer,
    minimum_minimum_nights integer,
    maximum_minimum_nights integer,
    minimum_maximum_nights integer,
    maximum_maximum_nights integer,
    minimum_nights_avg_ntm integer,
    maximum_nights_avg_ntm integer,
    calculated_host_listings_count_entire_homes integer,
    calculated_host_listings_count_private_rooms integer,
    calculated_host_listings_count_shared_rooms integer,
    PRIMARY KEY (id_regras),
    UNIQUE (fk_anuncio)
);

ALTER TABLE IF EXISTS b_silver."T_DIM_ANFITRIAO"
    ADD FOREIGN KEY (fk_anuncio)
    REFERENCES b_silver."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS b_silver."T_DIM_LOCALIZACAO"
    ADD FOREIGN KEY (fk_anuncio)
    REFERENCES b_silver."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS b_silver."T_DIM_PROPRIEDADE"
    ADD FOREIGN KEY (fk_anuncio)
    REFERENCES b_silver."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS b_silver."T_FATO_PRECIFICACAO"
    ADD FOREIGN KEY (fk_anuncio)
    REFERENCES b_silver."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS b_silver."T_FATO_AVALIACAO"
    ADD FOREIGN KEY (fk_anuncio)
    REFERENCES b_silver."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS b_silver."T_DIM_REGRAS"
    ADD FOREIGN KEY (fk_anuncio)
    REFERENCES b_silver."T_DIM_ANUNCIO" (id_anuncio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;